import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <script src="https://kit.fontawesome.com/51f89619a0.js" crossOrigin="anonymous" async ></script>
      <script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-element-bundle.min.js" async ></script>
      </head>
      <body className={inter.className + 'bg-white'}>{children}</body>
    </html>
  )
}
